---
# tasks file for apache
- name: "installation apache"
  yum:
    name: "httpd"
    state: "latest"

- name: "activation du service httpd"
  service: 
    name: "httpd"
    state: "started"
    enabled: yes

- name: "Installation de php7"
  include: php7-install.yml
  when: php_install|default(False)|bool