---
- name: "activation epel-release"
  yum: 
    name: "epel-release"
    state: present

- name: "activation repos remi"
  yum:
    name: "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    state : present

- name: "installation package php7"
  yum: 
    name: "php,php-mysql,php-xml,php-mbstring,php-mcrypt,php-gd,php-intl,php-pear,php-devel,php-fpm,httpd-devel,pcre-devel,gcc,make"
    state : latest
    enablerepo: "remi-php70"
  changed_when: yes
  notify: [ "apache restart" ]